name: Retrieve AWS Secret and Variable and Parameters

on:
  push:
    branches:
      - main
      - master
      - feature/*
      - develop

jobs:
  retrieve_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      # Firstly, insert your secrets in AWS Secret Manager
      # Then, you can retrieve the secrets based on your secret-id
      # If you have multiple secret key and value pairs like mine, you can parse
      # the entire json object and print the values you'd like to display/use

      - name: Get Secret Object
        run: |
          secret_object=$(aws secretsmanager get-secret-value --secret-id prod/luqman/hobby --query SecretString --output json)

          # Parse specific keys from the secret object
          secret_value_hobby=$(echo "$secret_object" | jq -r '. | fromjson | .luqman_hobby')
          secret_value_food=$(echo "$secret_object" | jq -r '. | fromjson | .luqman_food')
          secret_value_loc=$(echo "$secret_object" | jq -r '. | fromjson | .luqman_location')

          echo "Secret value Hobby is: $secret_value_hobby"
          echo "Secret value Food is: $secret_value_food"
          echo "Secret value Location is: $secret_value_loc"

  retrieve_parameters:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      # Firstly, insert your parameter in AWS Systems Manager > Parameter Store
      # Then, you can retrieve the parameters using aws ssm get-parameter command

      - name: Get parameter object
        run: |
          phone_value=$(aws ssm get-parameter --name luqman_phone --query Parameter.Value --output text)
          echo "Luqman's phone model is: $phone_value" 

          hobby_value=$(aws ssm get-parameter --name luqman_hobby --query Parameter.Value --output text)
          echo "Luqman's hobby is: $hobby_value" 
